In [1]:
from sympy import*
def transpose(matrix):
    print("Исходная матрица:\n")
    pprint(matrix)
    print("\nТранспонированная:\n")
    return matrix.T


In [2]:
matrix = Matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
pprint(transpose(matrix))

Исходная матрица:

⎡1   2   3   4 ⎤
⎢              ⎥
⎢5   6   7   8 ⎥
⎢              ⎥
⎢9   10  11  12⎥
⎢              ⎥
⎣13  14  15  16⎦

Транспонированная:

⎡1  5  9   13⎤
⎢            ⎥
⎢2  6  10  14⎥
⎢            ⎥
⎢3  7  11  15⎥
⎢            ⎥
⎣4  8  12  16⎦


In [3]:
import numpy as np
def transpose_matrix(matrix):
    if isinstance(matrix, np.ndarray):
        return matrix.T
    elif isinstance(matrix, list):
        return [list(row) for row in zip(*matrix)]
    else:
        raise ValueError("Неподдерживаемый тип данных.")
matrix1 = [
    [2, 1, 7, 4],
    [5, 6, 7, 3],
    [9, 8, 2, 12],
    [11, 14, 15, 15]
]
matrix2 = [
    [3, 7, 8, 3, 6],
    [2, 5, 9, 4, 13]
]
transposed_matrix1 = transpose_matrix(matrix1)
transposed_matrix2 = transpose_matrix(matrix2)
print("Транспонированная матрица 1 (list):")
for row in transposed_matrix1:
    print(row)

print("\nТранспонированная матрица 2 (list):")
for row in transposed_matrix2:
    print(row)
    
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

transposed_np_matrix1 = transpose_matrix(np_matrix1)
transposed_np_matrix2 = transpose_matrix(np_matrix2)

print("\nТранспонированная матрица 1 (numpy.array):")
print(transposed_np_matrix1)

print("\nТранспонированная матрица 2 (numpy.array):")
print(transposed_np_matrix2)

Транспонированная матрица 1 (list):
[2, 5, 9, 11]
[1, 6, 8, 14]
[7, 7, 2, 15]
[4, 3, 12, 15]

Транспонированная матрица 2 (list):
[3, 2]
[7, 5]
[8, 9]
[3, 4]
[6, 13]

Транспонированная матрица 1 (numpy.array):
[[ 2  5  9 11]
 [ 1  6  8 14]
 [ 7  7  2 15]
 [ 4  3 12 15]]

Транспонированная матрица 2 (numpy.array):
[[ 3  2]
 [ 7  5]
 [ 8  9]
 [ 3  4]
 [ 6 13]]


In [4]:
def mse(a1, a2):
    return 0.25 * ((a1 + 2*a2 - 5)**2 + (5*a1 + 3*a2 - 6)**2 + (2*a1 + 4*a2 - 10)**2 + (3*a1 + 7*a2 - 8)**2)
def gradient(a1, a2):
    df_da1 = 19.5 * a1 + 23 * a2 - 39.5
    df_da2 = 23 * a1 + 39 * a2 - 62
    return np.array([df_da1, df_da2])
a1, a2 = 0.57, 0.91
alpha = 0.01
steps = 0
while True:
    current_mse = mse(a1, a2)
    grad = gradient(a1, a2)
    a1 -= alpha * grad[0]
    a2 -= alpha * grad[1]
    steps += 1
    print(f"Шаг {steps}: (a1, a2) = ({a1:.4f}, {a2:.4f}), MSE = {current_mse:.4f}")
    if current_mse < 6.36:
        break

print(f"\nИтог: достигнуто MSE < 6.36 за {steps} шагов.")

Шаг 1: (a1, a2) = (0.6445, 1.0440), MSE = 8.5608
Шаг 2: (a1, a2) = (0.6737, 1.1086), MSE = 6.8435
Шаг 3: (a1, a2) = (0.6824, 1.1413), MSE = 6.4741
Шаг 4: (a1, a2) = (0.6818, 1.1592), MSE = 6.3879
Шаг 5: (a1, a2) = (0.6772, 1.1703), MSE = 6.3617
Шаг 6: (a1, a2) = (0.6710, 1.1781), MSE = 6.3487

Итог: достигнуто MSE < 6.36 за 6 шагов.
